Update train.py to fix line break
This commit broke this file : https://github.com/SullyChen/Autopilot-TensorFlow/commit/a6461fd9999da444cfd9c8976b540f3f118427e3

Error message:
  File "train.py", line 15
    + tf.add_n([tf.nn.l2_loss(v) for v in train_vars]) * L2NormConst
    ^
IndentationError: unexpected indent